name: github environemnts

on:
  workflow_dispatch:

jobs:
  get_env_vars:
    name: get env vars from a specific env
    runs-on: ubuntu-latest
    environment:
      name: dev_env
      url: https://github.com

    steps:
      - name: pull_secret_from_dev_env
        run : |
          echo "the value of dev_env_url is : ${{ secrets.DEV_ENV_URL }}"