name: environement variables demostration

on:
  workflow_dispatch:

env:
  DAY_OF_WEEK: funday
  testvar: workflow_level_scope

jobs:
  mainjob:
    name: "print env variables"
    runs-on: ubuntu-latest
    
    env:
      Greeting: Funday
      testvar: job_level_scope
    
    steps:
      - name: just a random step
        env:
          First_name: student
          testvar: step_scoped_var
        run: |
          echo "$Greeting $First_name. Today is a $DAY_OF_WEEK"
          echo "testvar $testvar"
          echo " testvar ${{ env.testvar }}"

