name: github action to handle secrets

on:
  workflow_dispatch:
  
jobs:
  mainjob:
    name: lets create some secrets
    runs-on: ubuntu-latest

    steps:
      - name : first step
        run: |

          echo "lets fetch a secret from git hub secrets"
          echo " the value of my secret is: ${{ secrets.TOP_SECRET }}"
          echo " I am not an existing secret: ${{ secrets.TOP_SECRET_THREE }}"
          echo "i am the top secret two printed using env: $secret_two"
        env:
          secret_two: ${{secrets.TOP_SECRET_TWO}}